// <auto-generated />
using System;
using DnDH.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDH.Repo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503173503_AddedSpellDbset")]
    partial class AddedSpellDbset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DnDH.Repo.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("DnDH.Repo.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("OtherProficiencies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SavingThrows")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Skills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DnDH.Repo.CharacterStateInCampaign", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CharacterStatesInCampaigns");
                });

            modelBuilder.Entity("DnDH.Repo.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeOfCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeOfUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("DnDH.Repo.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("DnDH.Repo.Spellcasting", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MaxSpellSlots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SpellSlots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellcastingAbility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("CharacterSpellcasting");
                });

            modelBuilder.Entity("DnDH.Repo.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpellSpellcasting", b =>
                {
                    b.Property<int>("CharacterSpellcastingCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnownSpellsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterSpellcastingCharacterId", "KnownSpellsId");

                    b.HasIndex("KnownSpellsId");

                    b.ToTable("SpellSpellcasting");
                });

            modelBuilder.Entity("DnDH.Repo.Campaign", b =>
                {
                    b.HasOne("DnDH.Repo.User", "Author")
                        .WithMany("Campaigns")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DnDH.Repo.Character", b =>
                {
                    b.HasOne("DnDH.Repo.User", "Owner")
                        .WithMany("Characters")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DnDH.Repo.Abilities", "Abilities", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Charisma")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Constitution")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Dexterity")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Intelligence")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Strength")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Wisdom")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("DnDH.Repo.Health", "Health", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("HitDice")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("HitPoints")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("MaxHitDice")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxHitPoints")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsOne("DnDH.Repo.Inventory", "Inventory", b1 =>
                        {
                            b1.Property<int>("CharacterId")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("EquippedItems")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Gold")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("OtherItems")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Abilities")
                        .IsRequired();

                    b.Navigation("Health")
                        .IsRequired();

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DnDH.Repo.CharacterStateInCampaign", b =>
                {
                    b.HasOne("DnDH.Repo.Campaign", "Campaign")
                        .WithMany("CharacterStatesInCampaigns")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDH.Repo.Character", "Character")
                        .WithMany("CharacterStatesInCampaigns")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DnDH.Repo.Note", b =>
                {
                    b.HasOne("DnDH.Repo.Campaign", "Campaign")
                        .WithMany("Notes")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DnDH.Repo.Spellcasting", b =>
                {
                    b.HasOne("DnDH.Repo.Character", "Character")
                        .WithOne("Spellcasting")
                        .HasForeignKey("DnDH.Repo.Spellcasting", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("SpellSpellcasting", b =>
                {
                    b.HasOne("DnDH.Repo.Spellcasting", null)
                        .WithMany()
                        .HasForeignKey("CharacterSpellcastingCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDH.Repo.Spell", null)
                        .WithMany()
                        .HasForeignKey("KnownSpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DnDH.Repo.Campaign", b =>
                {
                    b.Navigation("CharacterStatesInCampaigns");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("DnDH.Repo.Character", b =>
                {
                    b.Navigation("CharacterStatesInCampaigns");

                    b.Navigation("Spellcasting");
                });

            modelBuilder.Entity("DnDH.Repo.User", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
